# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    CrazyGoat\Forex\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    PhpAmqpLib\Connection\AMQPStreamConnection:
        arguments:
            $host: '%env(resolve:RABBITMQ_HOST)%'
            $port: '%env(resolve:RABBITMQ_PORT)%'
            $user: '%env(resolve:RABBITMQ_USER)%'
            $password: '%env(resolve:RABBITMQ_PASSWORD)%'
            $vhost: '%env(resolve:RABBITMQ_VHOST)%'

    # commands
    CrazyGoat\Forex\Command\SetupRabbit:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Draw\Command\History:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Command\CreateCandles:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Download\Histdata\Command\Download:
        tags: ['console.command']
    CrazyGoat\Forex\Download\Histdata\Command\DownloadMonth:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Download\Histdata\Command\PushToRabbit:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Command\ProcessTicks:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Stream\Oanda\Command\Stream:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\Stream\Stooq\Command\Stream:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\WebSocket\Command\TickStream:
        tags: [ 'console.command' ]
    CrazyGoat\Forex\WebSocket\TickServer:
        public: true
    CrazyGoat\Forex\Download\Stooq\Command\Download:
        tags: ['console.command']
        arguments:
            - '%kernel.cache_dir%'
    CrazyGoat\Forex\Download\Stooq\Command\PushToRabbit:
        tags: [ 'console.command' ]
        arguments:
            - '%kernel.cache_dir%'

    CrazyGoat\Forex\ML\Command\LearnDaily:
        tags: [ 'console.command' ]
        arguments:
            $cacheDir: '%kernel.cache_dir%'