App\Entity\TickData:
    type: entity
    table: tick_data
    id:
        symbol:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
            id: true
        time:
            type: datetime
            nullable: false
            id: true
    fields:
        bid:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
        ask:
            type: decimal
            nullable: false
            precision: 20
            scale: 6
    lifecycleCallbacks: {  }
